### PR TITLE
Changed row-seq and cell-seq to deal with blanks in spreadsheets

### PR DESCRIPTION
**Pull request by kornysietsma**
Fix for https://github.com/mjul/docjure/issues/19

Added `dense-row-seq`, `dense-cell-seq`, and `dense-select-columns` for reading sparse spreadsheets without skipping blanks.  Made new functions rather than changing existing ones, as the dense functions may be slower for large spreadsheets, and require extra handling of nil values.

Also fixed docstring for `remove-row!` (and added test) to clarify that rows are blanked, not removed.

Note I think there is still a problem calling `select-name` on a range with blanks, but that should be a separate issue (and separate pull request) when I get the chance.

### CODE REVIEW

**Comment by acron0** [comment]
Would be really good to see this fix...

**Comment by mjul** [comment]
Is this the best way to do it or would it fit better in the way we read sheets by default so we don't trouble the developer with a choice of two different sheet reading models?

**Comment by corroll** [comment]
How can I get access tis fix. I am trying to pass a bunch of xlsx some of which have empty cells.
I have 1.6.0 in my dependencies do i need to do anything else?

**Comment by kennycoc** [comment]
@mediasense if you want to use something in a pull request before it's merged, you'd either have to fork and apply the commits yourself, or use the fork the patch came from, and hope it's currently buildable

**Comment by kornysietsma** [comment]
@mediasense You could also just copy the dense functions from the pull request into a namespace of your own - the functions are really short, and should be pretty safe to use.

Alternatively as suggested at https://github.com/mjul/docjure/issues/19#issuecomment-169315802 you could use with-redefs to replace the original functions in a single scope.

**Comment by mjul** [comment]
It seems like a useful extension. Would you care to update it to the latest master and add your name to the contributor list.
Extra points will be awarded for adding an instructive example to the README.md so other users can benefit from your work.
Thank you for your contribution!

**Comment by kornysietsma** [comment]
Updated as per discussion on #19

**Pull request merged**
