### PR TITLE
Implemented dropdown list 

### PR DESCRIPTION
**Pull request by UbermenschJO**
Could you apply this change? thanks.

### CODE REVIEW

**Comment by russellwhitaker** [comment]
@UbermenschJO there are no tests included in this PR.

**Comment by UbermenschJO** [comment]
I added tests. check please?

**Comment by UbermenschJO** [comment]
@russellwhitaker check please :)

**Comment by russellwhitaker** [comment]
@UbermenschJO just saw this a year late... has conflicting files.

**Comment by russellwhitaker** [comment]
@mjul it looks like @UbermenschJO lost interest in this candidate PR, and didn't resolve conflicts... close it maybe?

**Comment by mjul** [comment]
OK, closing it for now.

**Pull request closed without merging**
