### PR TITLE
Add select-cell function for easy navigation in a worksheet

### PR DESCRIPTION
**Pull request by trieloff**
The select-cell function is a convenience wrapper around POI's CellReference and works similar to the other select-* functions in docjure.

I've added a simple unit and integration test.

### CODE REVIEW

**Comment by mjul** [comment]
It looks good, could you please add an example to the README.md showing how to use it, and while you are at it, add yourself to the list of contributors at the end of the README. Thanks

**Comment by trieloff** [comment]
Sure, will do.

**Comment by trieloff** [comment]
I've just pushed an update that has the documentation.

**Comment by mjul** [comment]
Thanks for helping out. It has now (finally!) been merged!

**Comment by trieloff** [comment]
Cool. I have another pull request coming that depends on this, but I need to make sure it is still up-to-date.

**Pull request merged**
