### PR TITLE
Update POI to 3.17

### PR DESCRIPTION
**Pull request by Macroz**
Implement minimal updates to support the new POI version 3.17 with enums.

Available at `macroz/docjure` 1.12.0 for use before PR is merged.

### CODE REVIEW

**Comment by mjul** [comment]
Looks good, thank you for contributing.

**Comment by mjul** [comment]
PS: next time, please remember to make sure the tests run before submitting a pull request.

**Comment by Macroz** [comment]
Sorry! I'm so used to CI running the tests on PR that I forgot to run the tests separately. I have my own project that I tested with but I'm definitely not using all the features.

Thanks for the library!

Are you planning on making a release soon?

**Comment by mjul** [comment]
I pushed a release to Clojars a moment ago.
If you know how to set up automatic CI for the GitHub project I would appreciate a pull request.
Thanks, Martin

**Comment by Macroz** [comment]
I can see that you have a starter `.travis.yml` already in the root of the project. So you could just 

- go to https://travis-ci.org
- login with GitHub account
- search for `mjul/docjure`
- enable Travis for the project

After that all PRs should get tested. You can read about other features from the Travis pages. E.g. you could tune which JDK is supported etc. This I think is the easiest way to get started!

**Comment by mjul** [comment]
Done. Thanks for your help.

**Pull request merged**
